### ISSUE TITLE
endpoints outside of /v0

### ISSUE THREAD

**Issue by theapplicationist** [wavesplatform/data-service#85]
The latest clients makes calls to an API 1 level above /v0/ for example; 

`https://api.wavesplatform.com/assets/search/bitcoin`

and
`https://api.wavesplatform.com/candles/WAVES/Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck?timeStart=1532080038877&timeEnd=1534758438879&interval=223m`

But these are not handled by the service. Is there another service thats not published here, or is this code out of date? I'm service this repo on the /v0/ path

cc @dvshur

**Comment by dvshur** [comment]
@theapplicationist, thank you for you attention to our codebase.

The endpoints you mention — `/assets/search` and `/candles` — are indeed not handled by this service. They are handled by old legacy servers. **It's not a v1 API**, it's an old API that came before any kind of versioning, which is the reason it's outside of /v0.

We consider those APIs legacy, as well as [marketdata.wavesplatform.com](https://marketdata.wavesplatform.com). They are not going to be further developed or actively supported and should be considered _deprecated_.

We still continue to use them only because so far we've been focusing our efforts on developing new features, postponing some refactoring and restructuring until later. It is our intention to gradually migrate all our products to properly versioned and structured APIs.

**Comment by theapplicationist** [comment]
Ah I understand. Thanks for getting back to me. 
Despite these being deprecated, are you able to share the code or spec of that API? I'm running a client against a custom blockchain so unable to render candles (Or pinned asset search) without this.

**Comment by dvshur** [comment]
Sorry for taking long to respond, we don't have much spare time at the moment as we're somewhat shorthanded. I don't think I could quickly dig up the code for those, but the spec looks like:

`/assets/search/${textQuery}`
`/candles/{amountAssetId}/{priceAssetId}?timeStart={timestamp}&timeEnd={timestamp}&interval={interval}`
interval examples — `60m`, `12h`, `1d`

Example of assets request:
https://api.wavesplatform.com/assets/search/bit

Example of candles request:
https://api.wavesplatform.com/candles/474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu/WAVES?timeStart=1507198441000&timeEnd=1512382501000&interval=60m

Hope it helps. We'll try to migrate to new APIs as quickly as possible, however, we currently have several more urgent tasks to take care of first.
